### ISSUE TITLE
French Keyboard Layout

### ISSUE THREAD

**Issue by loic-fejoz** [f4iey/f6kgl-os#2]
- French Keyboard Layout (Azerty) should be available in the default layout
- Keyboard Widget should be by default in the bottom bar

**Comment by f4iey** [comment]
At the moment, it is possible to set the keyboard layout just by using `setxkbmap fr` on the live environment.
It can also be done during the system installation with Calamares or the KDE system settings.
I know how annoying it is (knowing, of course, most people are french users). I will check it out

**Comment by f4iey** [comment]
#3 
![image](https://user-images.githubusercontent.com/93203507/151174870-f4826817-f38f-44e4-bae4-1e0acd5203ca.png)

**Comment by loic-fejoz** [comment]
I know those arcane command indeed but not everyone is accustomed to Linux in the community, so to changing keyboard stuff... ;-)
