### ISSUE TITLE
Wsjtx missing libboost_log_setup.so.1.76.0

### ISSUE THREAD

**Issue by loic-fejoz** [f4iey/f6kgl-os#4]
Out of the box, it seems wsjtx cannot work.
```
liveuser@f6kgl ~ % wsjtx
wsjtx: error while loading shared libraries: libboost_log_setup.so.1.76.0: cannot open shared object file: No such file or directory

```

**Comment by f4iey** [comment]
It has been pactched in the latest PKGBUILD [from the AUR](https://aur.archlinux.org/packages/wsjtx)
The package on the f6kgl-repo has also been updated to this version: [#ce8a6e203987400fc83976e41f4937ee4df852e5](https://gitlab.com/f4iey/f6kgl-repo/-/commit/ce8a6e203987400fc83976e41f4937ee4df852e5).
